# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
Version: 1
Packages:
- shinycssloaders
- furrr
- TrialSize
- PropCIs
- profvis
- DiagrammeR
- DiagrammeRsvg
- devtools
- padr
- plotly
- extrafont
- proj4
- ash
- maps
- anytime
- assertthat
- BH
- bitops
- blockrand
- broom
- caTools
- covr
- crayon
- data.table
- devtools
- devutils
- digest
- dplyr
- ggplot2
- ggrepel
- ggridges
- gt
- knitr
- logrrr
- magrittr
- mc2d
- miniCRAN
- miniUI
- mrgsolve
- pkgpub
- PKPDmisc
- purrr
- R6
- remotes
- rlang
- rmarkdown
- rrsq
- rstudioapi
- rvest
- sessioninfo
- shiny
- shinydashboard
- survminer
- testthat
- tibble
- tidyr
- tidyverse
- usethis
- whisker
- xml2
- yaml
Suggests: true
Repos:
- gh_external: https://metrumresearchgroup.github.io/rpkgs/gh_external
- gh_dev: https://metrumresearchgroup.github.io/rpkgs/gh_dev
- CRAN: https://cran.microsoft.com/snapshot/2019-03-15
Library: '3.5'
Cache: pkgcache
Customizations:
  Packages:
  - devtools:
      Type: source
